---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awx-ee-rolebinding
  namespace: apps
subjects:
  - kind: ServiceAccount
    name: awx-ee-sa
    namespace: apps
roleRef:
  kind: Role
  name: awx-ee-role
  apiGroup: rbac.authorization.k8s.io
